version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./my/own/datadir:/var/lib/mysql
    ports: 
     - 8080:8080